### ISSUE TITLE
Prevent users from `?flush`

### ISSUE THREAD

**Issue by dhensby** [silverstripe/demo.silverstripe.org#11]
We shouldn't really let anyone flush the site from the URL on this site

note we provide users with admin creds to be able to test the CMS, they then get the rights to flush, build, etc. We should think about locking these down from the URL

**Comment by dhensby** [comment]
still a problem

**Comment by GuySartorelli** [comment]
All of the `/dev/*` routes can now be locked down using permissions (see https://docs.silverstripe.org/en/5/changelogs/5.2.0/#dev-route-permissions)
Does this solve your use case?

**Comment by dhensby** [comment]
seems to be fixed - going to demo and trying to flush forwards to a login page
