### ISSUE TITLE
Language support link on the HP goes to ss3 subdomain

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/demo.silverstripe.org#44]
As per the title...

![Screen Shot 2020-05-11 at 9 22 39 PM](https://user-images.githubusercontent.com/233342/81546773-f5868000-93ce-11ea-8de8-e54a9454cc3b.png)

There are a bunch of other old and test URLs on the site too.

## PRs
- https://github.com/silverstripe/demo.silverstripe.org/pull/65

**Comment by GuySartorelli** [comment]
PR merged
