### ISSUE TITLE
Content improvements for demo e.g. use of old SilverStripe wording

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/demo.silverstripe.org#51]
There are loads of instances where the old usage of _SilverStripe_ still remains. 

- All content areas referring to SilverStripe should be updated to use _Silverstripe_ or _Silverstripe CMS_ in all cases.
- Site name _SilverStripe demo_ to use _Silverstripe CMS demo_ .
- ~Loads of other grammatical errors and improvements could be made within content areas (e.g. using Grammarly or similar will show them)~ The demo will be completely rebuilt so we're not going to spend that much effort on it

## PRs
- https://github.com/silverstripe/demo.silverstripe.org/pull/65

**Comment by GuySartorelli** [comment]
PR merged. Deployment will be handled in https://github.com/silverstripeltd/product-issues/issues/813
