### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/demo.silverstripe.org#63]
Demo is broken. Not sure why.

## Acceptance criteria
- Demo is not broken
- Reasonable steps are put in place to avoid the demo breaking again.
 
## Note
This demo is (hopefully) not long for this world. Not sure it's worth putting monitoring in there to detect when it crashes.

**Comment by GuySartorelli** [comment]
Support ticket raised: https://servicedesk.silverstripe.cloud/support/tickets/111598

**Comment by GuySartorelli** [comment]
Demo is back up
